[tool.poetry]
name = "o365creeper-ng"
version = "0.1.0"
description = "Stealthy o365 user validation"
authors = ["mchoji <mchoji@users.noreply.github.com>"]
license = "BSD 2-Clause"

[tool.poetry.dependencies]
python = "^3.8"
requests = {extras = ["socks", "security"], version = "^2.25.1"}
stem = "^1.8.0"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
yapf = "^0.32.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
